<?php

namespace App\Http\Traits;

Trait HelperTrait
{
    public function formataCaracteresEspeciais($value){
      $value = str_replace(' ', '', $value);
      $value = str_replace('ç', 'c', $value);
      $value = str_replace('Ç', 'C', $value);
      $value = str_replace('á', 'a', $value);
      $value = str_replace('Á', 'A', $value);
      $value = str_replace('é', 'e', $value);
      $value = str_replace('É', 'E', $value);
      $value = str_replace('í', 'i', $value);
      $value = str_replace('Í', 'I', $value);
      $value = str_replace('ó', 'o', $value);
      $value = str_replace('Ó', 'O', $value);
      $value = str_replace('ú', 'u', $value);
      $value = str_replace('Ú', 'U', $value);
      $value = str_replace('â', 'a', $value);
      $value = str_replace('Â', 'A', $value);
      $value = str_replace('ê', 'e', $value);
      $value = str_replace('Ê', 'E', $value);
      $value = str_replace('ô', 'o', $value);
      $value = str_replace('Ô', 'O', $value);
      $value = str_replace('ã', 'a', $value);
      $value = str_replace('Ã', 'A', $value);
      $value = str_replace('õ', 'o', $value);
      $value = str_replace('Õ', 'O', $value);
      $value = str_replace('à', 'a', $value);
      $value = str_replace('À', 'A', $value);
      $value = str_replace('è', 'e', $value);
      $value = str_replace('È', 'E', $value);
      $value = str_replace('ì', 'i', $value);
      $value = str_replace('Ì', 'I', $value);
      $value = str_replace('ò', 'o', $value);
      $value = str_replace('Ò', 'O', $value);
      $value = str_replace('ù', 'u', $value);
      $value = str_replace('Ù', 'U', $value);
      $value = str_replace('ä', 'a', $value);
      $value = str_replace('Ä', 'A', $value);
      $value = str_replace('ë', 'e', $value);
      $value = str_replace('Ë', 'E', $value);
      $value = str_replace('ï', 'i', $value);
      $value = str_replace('Ï', 'I', $value);
      $value = str_replace('ö', 'o', $value);
      $value = str_replace('Ö', 'O', $value);
      $value = str_replace('ü', 'u', $value);
      $value = str_replace('Ü', 'U', $value);
      $value = str_replace('ÿ', 'y', $value);
      $value = str_replace('Ÿ', 'Y', $value);
      $value = str_replace('ñ', 'n', $value);
      $value = str_replace('Ñ', 'N', $value);
      $value = str_replace('ý', 'y', $value);
      $value = str_replace('Ý', 'Y', $value);
      $value = str_replace('š', 's', $value);
      $value = str_replace('Š', 'S', $value);
      $value = str_replace('ž', 'z', $value);
      $value = str_replace('Ž', 'Z', $value);
      $value = str_replace('æ', 'ae', $value);
      $value = str_replace('Æ', 'AE', $value);
      $value = str_replace('œ', 'oe', $value);
      $value = str_replace('Œ', 'OE', $value);
      $value = str_replace('ß', 'ss', $value);
      $value = str_replace('Þ', 'TH', $value);
      $value = str_replace('þ', 'th', $value);
      $value = str_replace('ð', 'dh', $value);
      $value = str_replace('Ð', 'DH', $value);
      $value = str_replace('µ', 'u', $value);
      $value = str_replace('µ', 'U', $value);
      $value = str_replace('º', 'o', $value);
      $value = str_replace('º', 'O', $value);
      $value = str_replace('ª', 'a', $value);
      $value = str_replace('ª', 'A', $value);
      $value = str_replace('°', 'o', $value);
      $value = str_replace('°', 'O', $value);
      $value = str_replace('º', 'o', $value);
      $value = str_replace('º', 'O', $value);
      $value = str_replace('ª', 'a', $value);
      $value = str_replace('ª', 'A', $value);
      $value = str_replace('°', 'o', $value);
      $value = str_replace('°', 'O', $value);
      $value = str_replace('º', 'o', $value);
      $value = str_replace('º', 'O', $value);
      $value = str_replace('ª', 'a', $value);
      $value = str_replace('ª', 'A', $value);
      $value = str_replace('°', 'o', $value);
      $value = str_replace('°', 'O', $value);
      $value = str_replace('º', 'o', $value);
      $value = str_replace('º', 'O', $value);
      $value = str_replace('ª', 'a', $value);
      $value = str_replace('ª', 'A', $value);
      $value = str_replace('°', 'o', $value);
      $value = str_replace('°', 'O', $value);
      $value = str_replace('º', 'o', $value);
      $value = str_replace('º', 'O', $value);
      $value = str_replace('ª', 'a', $value);
      $value = str_replace('ª', 'A', $value);
      $value = str_replace('°', 'o', $value);
      $value = str_replace('°', 'O', $value);
      $value = str_replace('º', 'o', $value);
      return $value;
    }
}